version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  checkout_code:
    executor: machine-executor
    steps:
      - checkout

  build:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            echo "Building the project..."

  add_ssh_keys:
    executor: machine-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:i5UbLMGKVZklg0ecFB36Tq59RNt/nsnXGAS9HduVry0"

  install_sonar_scanner:
    executor: machine-executor
    steps:
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip openjdk-17-jdk
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            echo "Downloaded sonar-scanner-cli.zip:"
            ls -al sonar-scanner-cli.zip
            sudo unzip sonar-scanner-cli.zip -d /usr/local/
            echo "Extracted sonar-scanner-cli.zip:"
            ls -al /usr/local/sonar-scanner-4.7.0.2747-linux
            sudo mv /usr/local/sonar-scanner-4.7.0.2747-linux /usr/local/sonar-scanner
            sudo chmod -R 755 /usr/local/sonar-scanner
            echo "After moving and setting permissions:"
            ls -al /usr/local/
            ls -al /usr/local/sonar-scanner
            ls -al /usr/local/sonar-scanner/bin

  deploy:
    executor: machine-executor
    steps:
      - run:
          name: Deploy to Azure VM
          command: |
            ssh -i ~/.ssh/test_key.pem azureuser@172.205.227.20 "cd /opt/lampp/htdocs/mutillidae && git pull origin main && sudo /opt/lampp/lampp restart"

  run_sonar_scanner:
    executor: machine-executor
    environment:
      JAVA_HOME: /usr/lib/jvm/openjdk-17
      PATH: /usr/local/sonar-scanner/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - run:
          name: Set Environment Variables
          command: |
            export JAVA_HOME=/usr/lib/jvm/openjdk-17
            export PATH=$PATH:/usr/local/sonar-scanner/bin
            echo "JAVA_HOME is set to $JAVA_HOME"
            echo "PATH is set to $PATH"
            echo "Checking /usr/local/sonar-scanner directory:"
            ls -al /usr/local/sonar-scanner
            echo "Checking /usr/local/sonar-scanner/bin directory:"
            ls -al /usr/local/sonar-scanner/bin
      - run:
          name: Run SonarScanner
          command: |
            /usr/local/sonar-scanner/bin/sonar-scanner \
              -Dsonar.projectKey=rozsherry \
              -Dsonar.organization=rozsherry \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=2b7433c963f8695daaa149d9edb1f3f20f07f332

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - add_ssh_keys:
          requires:
            - build
      - deploy:
          requires:
            - add_ssh_keys
      - install_sonar_scanner:
          requires:
            - deploy
      - run_sonar_scanner:
          requires:
            - install_sonar_scanner
