version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  checkout_code:
    executor: machine-executor
    steps:
      - checkout

  build:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            echo "Building the project..."

  add_ssh_keys:
    executor: machine-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:i5UbLMGKVZklg0ecFB36Tq59RNt/nsnXGAS9HduVry0"

  deploy:
    executor: machine-executor
    steps:
      - run:
          name: Deploy to Azure VM
          command: |
            ssh -i ~/.ssh/test_key.pem azureuser@172.205.227.20 "cd /opt/lampp/htdocs/mutillidae && git pull origin main && sudo /opt/lampp/lampp restart"

  download_extract_install_owasp_zap:
    executor: machine-executor
    steps:
      - run:
          name: Download OWASP ZAP
          command: |
            wget -O ZAP_2.11.0_Linux.tar.gz https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz
      - run:
          name: Extract OWASP ZAP
          command: |
            tar -xf ZAP_2.11.0_Linux.tar.gz
      - run:
          name: Install OWASP ZAP Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            export PATH=$PATH:$(pwd)/ZAP_2.11.0

  run_owasp_zap:
    executor: machine-executor
    steps:
      - run:
          name: Run OWASP ZAP
          command: |
            zap-baseline.py -t http://172.205.227.20/mutillidae/ -r owasp_report.html

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - add_ssh_keys:
          requires:
            - build
      - deploy:
          requires:
            - add_ssh_keys
      - download_extract_install_owasp_zap:
          requires:
            - deploy
      - run_owasp_zap:
          requires:
            - download_extract_install_owasp_zap
