executors:
  custom-executor:
    docker:
      - image: dockerimg:latest
        environment:
          DOCKER_USERNAME: $DOCKER_USERNAME
          DOCKER_PASSWORD: $DOCKER_PASSWORD

jobs:
  checkout_code:
    executor: custom-executor
    steps:
      - checkout

  build:
    executor: custom-executor
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            echo "Building the project..."

  login_to_docker_hub:
    executor: custom-executor
    steps:
      - run:
          name: Login to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  add_ssh_keys:
    executor: custom-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:i5UbLMGKVZklg0ecFB36Tq59RNt/nsnXGAS9HduVry0"

  deploy:
    executor: custom-executor
    steps:
      - run:
          name: Deploy to Azure VM
          command: |
            ssh -i ~/.ssh/test_key.pem azureuser@172.205.227.20 "cd /opt/lampp/htdocs/mutillidae && git pull origin main && sudo /opt/lampp/lampp restart"

  run_sonar_scanner:
    executor: custom-executor
    steps:
      - run:
          name: Verify SonarScanner Installation
          command: |
            echo "JAVA_HOME is set to $JAVA_HOME"
            echo "PATH is set to $PATH"
            echo "Checking /usr/local/sonar-scanner directory:"
            ls -al /usr/local/sonar-scanner
            echo "Checking /usr/local/sonar-scanner/bin directory:"
            ls -al /usr/local/sonar-scanner/bin
      - run:
          name: Run SonarScanner
          command: |
            /usr/local/sonar-scanner/bin/sonar-scanner \
              -Dsonar.projectKey=rozsherry \
              -Dsonar.organization=rozsherry \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=2b7433c963f8695daaa149d9edb1f3f20f07f332

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - login_to_docker_hub: # Ajout de l'étape de connexion à Docker Hub
          requires:
            - build
      - add_ssh_keys:
          requires:
            - login_to_docker_hub # Modification de l'exigence
      - deploy:
          requires:
            - add_ssh_keys
      - run_sonar_scanner:
          requires:
            - deploy
