version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  checkout_code:
    executor: machine-executor
    steps:
      - checkout

  build:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            echo "Building the project..."

  add_ssh_keys:
    executor: machine-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:i5UbLMGKVZklg0ecFB36Tq59RNt/nsnXGAS9HduVry0"

  install_sonar_scanner:
    executor: machine-executor
    steps:
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip openjdk-17-jdk
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            sudo unzip sonar-scanner-cli.zip -d /usr/local/
            sudo mv /usr/local/sonar-scanner-4.7.0.2747-linux /usr/local/sonar-scanner
            sudo chmod -R 755 /usr/local/sonar-scanner
      - run:
          name: Update PATH for SonarScanner
          command: echo 'export PATH=$PATH:/usr/local/sonar-scanner/bin' >> $BASH_ENV

  deploy:
    executor: machine-executor
    steps:
      - run:
          name: Deploy to Azure VM
          command: |
            ssh -i ~/.ssh/test_key.pem azureuser@172.205.227.20 "cd /opt/lampp/htdocs/mutillidae && git pull origin main && sudo /opt/lampp/lampp restart"

  run_sonar_scanner:
    executor: machine-executor
    steps:
      - run:
          name: Load Environment Variables
          command: source $BASH_ENV
      - run:
          name: Run SonarScanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=rozsherry \
              -Dsonar.organization=rozsherry \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=2b7433c963f8695daaa149d9edb1f3f20f07f332

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - add_ssh_keys:
          requires:
            - build
      - deploy:
          requires:
            - add_ssh_keys
      - install_sonar_scanner:
          requires:
            - deploy
      - run_sonar_scanner:
          requires:
            - install_sonar_scanner
