version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  checkout_code:
    executor: machine-executor
    steps:
      - checkout

  build:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            echo "Building the project..."

  add_ssh_keys:
    executor: machine-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:i5UbLMGKVZklg0ecFB36Tq59RNt/nsnXGAS9HduVry0"

  install_sonar_scanner:
    executor: machine-executor
    steps:
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl unzip openjdk-17-jdk
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            sudo unzip sonar-scanner-cli.zip -d /usr/local/
            sudo mv /usr/local/sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner
            sudo chmod -R 755 /opt/sonar-scanner
      - run:
          name: Verify SonarScanner Installation
          command: |
            ls -l /opt/sonar-scanner/bin
            /opt/sonar-scanner/bin/sonar-scanner --version

  deploy:
    executor: machine-executor
    steps:
      - run:
          name: Deploy to Azure VM
          command: |
            ssh -i ~/.ssh/test_key.pem azureuser@172.205.227.20 "cd /opt/lampp/htdocs/mutillidae && git pull origin main && sudo /opt/lampp/lampp restart"

  check_sonar_scanner:
    executor: machine-executor
    steps:
      - run:
          name: Check SonarScanner Path
          command: |
            echo "Listing files in /opt/sonar-scanner/bin"
            ls -l /opt/sonar-scanner/bin
            if [ ! -f /opt/sonar-scanner/bin/sonar-scanner ]; then
              echo "SonarScanner executable not found!"
              exit 1
            fi
            echo "SonarScanner executable found."
            ls -l /opt/sonar-scanner/bin/sonar-scanner

  run_sonar_scanner:
    executor: machine-executor
    environment:
      JAVA_HOME: /usr/lib/jvm/openjdk-17
      PATH: /opt/sonar-scanner/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - run:
          name: Set Environment Variables
          command: |
            export JAVA_HOME=/usr/lib/jvm/openjdk-17
            export PATH=$PATH:/opt/sonar-scanner/bin
            echo "JAVA_HOME is set to $JAVA_HOME"
            echo "PATH is set to $PATH"
      - run:
          name: Run SonarScanner
          command: |
            /opt/sonar-scanner/bin/sonar-scanner \
              -Dsonar.projectKey=rozsherry \
              -Dsonar.organization=rozsherry \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=2b7433c963f8695daaa149d9edb1f3f20f07f332

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - add_ssh_keys:
          requires:
            - build
      - deploy:
          requires:
            - add_ssh_keys
      - install_sonar_scanner:
          requires:
            - deploy
      - check_sonar_scanner:
          requires:
            - install_sonar_scanner
      - run_sonar_scanner:
          requires:
            - check_sonar_scanner
